# This file is generated by composer-plugin-nixify.
# Manual changes might be lost - proceed with caution!

{ lib, php, phpPackages, unzip, stdenv, runCommandLocal, writeText, fetchurl

# Default fetcher.
, fetcher ? (args: fetchurl { inherit (args) name urls sha256; })

}: src:

with lib;

let
  data = builtins.fromJSON ''
    {
    "cacheEntries": [
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "dflydev_dot-access-data-3.0.2.0",
            "urls": [
                "https://api.github.com/repos/dflydev/dflydev-dot-access-data/zipball/f41715465d65213d644d3141a6a93081be5d3549"
            ],
            "cacheFile": "dflydev/dot-access-data/5872417a18bbb69b106dc09a3b09c46b193e0110.zip",
            "sha256": "b2ae92836d920d2a968b32acd80e1c39a1446c749ddae28dc806408c7096ebed"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_cache-2.2.0.0",
            "urls": [
                "https://api.github.com/repos/doctrine/cache/zipball/1ca8f21980e770095a31456042471a57bc4c68fb"
            ],
            "cacheFile": "doctrine/cache/3d10cdf80c6a538fe80c85b81ed43c4c89c2e472.zip",
            "sha256": "5a8799a67c97aab8a40b91eaa5a7af2db2e7c2b301a34ef60ae7e33a5e5211dd"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_collections-2.1.2.0",
            "urls": [
                "https://api.github.com/repos/doctrine/collections/zipball/db8cda536a034337f7dd63febecc713d4957f9ee"
            ],
            "cacheFile": "doctrine/collections/21661d86f5bff879b583a6fbd24f913eeed1967e.zip",
            "sha256": "4cdd9a7274821e3b40a8973c2a654443023318c11729127788026ca70ee0c2db"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_common-3.4.3.0",
            "urls": [
                "https://api.github.com/repos/doctrine/common/zipball/8b5e5650391f851ed58910b3e3d48a71062eeced"
            ],
            "cacheFile": "doctrine/common/b5038a8d0612b9cfdce6b30aeb4bb0cef00dfe3e.zip",
            "sha256": "2722d43a5e727afdcb82065732e0c71179c4114a179e2bd454b96025f0c1e382"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_dbal-3.5.3.0",
            "urls": [
                "https://api.github.com/repos/doctrine/dbal/zipball/88fa7e5189fd5ec6682477044264dc0ed4e3aa1e"
            ],
            "cacheFile": "doctrine/dbal/0678885ed14367e002e67c52f5edd8874df33f8a.zip",
            "sha256": "5a61d517dfc709d43390caf6de408b579803fe084c6549d64767a00cb0f7e7f7"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_deprecations-1.0.0.0",
            "urls": [
                "https://api.github.com/repos/doctrine/deprecations/zipball/0e2a4f1f8cdfc7a92ec3b01c9334898c806b30de"
            ],
            "cacheFile": "doctrine/deprecations/0b11d410b30a1fca6ad657a01bbf1bf8cb37b15b.zip",
            "sha256": "0948892861e2470c164fb0c45063967417c4b9e527ea4cf2b987030b047061ea"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_doctrine-bundle-2.8.2.0",
            "urls": [
                "https://api.github.com/repos/doctrine/DoctrineBundle/zipball/251cd5aaea32bb92cdad4204840786b317dcdd4c"
            ],
            "cacheFile": "doctrine/doctrine-bundle/43b77048fde7b54a48e2b2c6e10ce8c70f18e1cd.zip",
            "sha256": "81fb2020f40f7b3771c7846d7e157a5f77fee9e93a44181d4db0f80d57613f6a"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_doctrine-migrations-bundle-3.2.2.0",
            "urls": [
                "https://api.github.com/repos/doctrine/DoctrineMigrationsBundle/zipball/3393f411ba25ade21969c33f2053220044854d01"
            ],
            "cacheFile": "doctrine/doctrine-migrations-bundle/1f9868c4757b79572459b7a20aff9024345bf454.zip",
            "sha256": "f90d83ed4827a336156bb73a7624fda2ff94d46f2e24d40f1a145c8bec1d9880"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_event-manager-2.0.0.0",
            "urls": [
                "https://api.github.com/repos/doctrine/event-manager/zipball/750671534e0241a7c50ea5b43f67e23eb5c96f32"
            ],
            "cacheFile": "doctrine/event-manager/4b9ceebabffaa3f93e82b47b73e38ac7cd2a6964.zip",
            "sha256": "d0b181c6e836fd6b83672042959d947e3017416f4bf7d261360d4585e680d0c6"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_inflector-2.0.6.0",
            "urls": [
                "https://api.github.com/repos/doctrine/inflector/zipball/d9d313a36c872fd6ee06d9a6cbcf713eaa40f024"
            ],
            "cacheFile": "doctrine/inflector/57c027282263baa14000cf3525eb68a5f0795e45.zip",
            "sha256": "12dae3b88886e0adde83b1d7338d2df7480620a0ec5ec8cde15935857b05defc"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_instantiator-1.5.0.0",
            "urls": [
                "https://api.github.com/repos/doctrine/instantiator/zipball/0a0fa9780f5d4e507415a065172d26a98d02047b"
            ],
            "cacheFile": "doctrine/instantiator/281539f78a082d6b6f518e4643e807bb44376df5.zip",
            "sha256": "b2ac699a2ce6afe19db094650009e81eb0471d8cbfaa7a8bb4825e88e6011b03"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_lexer-2.1.0.0",
            "urls": [
                "https://api.github.com/repos/doctrine/lexer/zipball/39ab8fcf5a51ce4b85ca97c7a7d033eb12831124"
            ],
            "cacheFile": "doctrine/lexer/b4234cb7c4536da25e7669362cfb87940f58d05f.zip",
            "sha256": "50bde7a5b68b6ef697044ed6256605a3bf19b106491dcbea5dc569041d9a6aa6"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_migrations-3.5.5.0",
            "urls": [
                "https://api.github.com/repos/doctrine/migrations/zipball/4b1e2b6ba71d21d0c5be22ed03b6fc954d20b204"
            ],
            "cacheFile": "doctrine/migrations/2d3abfd51d379fac30a0f6ad0b8f8687edb1ed8b.zip",
            "sha256": "66e819e1b97fd68b2c52496bc605a7ac68411b93636b37c5012fa55893b7122b"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_orm-2.14.1.0",
            "urls": [
                "https://api.github.com/repos/doctrine/orm/zipball/de7eee5ed7b1b35c99b118f26f210a8281e6db8e"
            ],
            "cacheFile": "doctrine/orm/52670d585799e5b47d115008ceeb83a423eaabfc.zip",
            "sha256": "ab45add3e7cc56402026e8b1b5db66a9d64edd3c287166cf8b7f028b84669da6"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_persistence-3.1.3.0",
            "urls": [
                "https://api.github.com/repos/doctrine/persistence/zipball/920da294b4bb0bb527f2a91ed60c18213435880f"
            ],
            "cacheFile": "doctrine/persistence/acabef3c2eee9955ef9c8726aca0fbf0c05e7661.zip",
            "sha256": "72cd314f4377c34a8bc6432c6ae341af59d4637d4e6fcca74020c6fd603a5c09"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_sql-formatter-1.1.3.0",
            "urls": [
                "https://api.github.com/repos/doctrine/sql-formatter/zipball/25a06c7bf4c6b8218f47928654252863ffc890a5"
            ],
            "cacheFile": "doctrine/sql-formatter/27cb22cc3ac9fadaf29e9fdfc567a5373f122417.zip",
            "sha256": "835e8606783efcf94feb9bee7987bf67a47d27d0ba709bd4425a06a56bd61b6e"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "drupol_composer-plugin-nixify-2.0.7.0",
            "urls": [
                "https://api.github.com/repos/drupol/composer-plugin-nixify/zipball/56ece5e20dfa9402dd4058be35b893a08ed8aff1"
            ],
            "cacheFile": "drupol/composer-plugin-nixify/1e9ddfb441ea884c3aa529d65a4967447fd35c84.zip",
            "sha256": "8aff72b29081cd057dd4c87ca874ea0f67f8ae82cd879ee4824b311c9993d459"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "egulias_email-validator-4.0.1.0",
            "urls": [
                "https://api.github.com/repos/egulias/EmailValidator/zipball/3a85486b709bc384dae8eb78fb2eec649bdb64ff"
            ],
            "cacheFile": "egulias/email-validator/f2b96d737edce903bd0aa35aa9afc48c74fffe35.zip",
            "sha256": "bcaf356b0877d68b858783646c4bbf9fcb569c9aff36e0dd052199f71c697ced"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "friendsofphp_proxy-manager-lts-1.0.13.0",
            "urls": [
                "https://api.github.com/repos/FriendsOfPHP/proxy-manager-lts/zipball/88354616f4cf4f6620910fd035e282173ba453e8"
            ],
            "cacheFile": "friendsofphp/proxy-manager-lts/3741de9b1fbac34869f82570083768f2d96eadb2.zip",
            "sha256": "378a4cd426c3238f6ad90151b2bab09cd344b51b58ee77e514fecc0e1926d950"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "laminas_laminas-code-4.8.0.0",
            "urls": [
                "https://api.github.com/repos/laminas/laminas-code/zipball/dd19fe8e07cc3f374308565667eecd4958c22106"
            ],
            "cacheFile": "laminas/laminas-code/6f11a7a94105d2d80cd1526f8654e489a3d28ce9.zip",
            "sha256": "526805e1702429ec7e30e00a01e7611236d54cf3f9886e7723e0561fefd90388"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "league_commonmark-2.3.8.0",
            "urls": [
                "https://api.github.com/repos/thephpleague/commonmark/zipball/c493585c130544c4e91d2e0e131e6d35cb0cbc47"
            ],
            "cacheFile": "league/commonmark/378a63195644b8080db12fb35208f3fc3ab8acf0.zip",
            "sha256": "4a2af02687a4966271285dc1ccff0f2af2192396b6ee1097a53dc7d4ba23bc7c"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "league_config-1.2.0.0",
            "urls": [
                "https://api.github.com/repos/thephpleague/config/zipball/754b3604fb2984c71f4af4a9cbe7b57f346ec1f3"
            ],
            "cacheFile": "league/config/63acc0c0da84dd8710b3a4e58a6a4e393530da19.zip",
            "sha256": "1ad93a2858d4479e29d29b88d0d3e4ac4221631b06959454ae4061d058414b7a"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "league_uri-6.8.0.0",
            "urls": [
                "https://api.github.com/repos/thephpleague/uri/zipball/a700b4656e4c54371b799ac61e300ab25a2d1d39"
            ],
            "cacheFile": "league/uri/d78e0e6337937a14dc8ddf00677ad4fccc5b2629.zip",
            "sha256": "5eabb50df8a715ed68f9fa86a996e25569f88e2e8599eb33cd32f8abaa1150ea"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "league_uri-interfaces-2.3.0.0",
            "urls": [
                "https://api.github.com/repos/thephpleague/uri-interfaces/zipball/00e7e2943f76d8cb50c7dfdc2f6dee356e15e383"
            ],
            "cacheFile": "league/uri-interfaces/abbfdfd0d9b6d6497ac2b5bcb6327c7ddd61493d.zip",
            "sha256": "dd6ca9a52521d7841729e3df05f16c679e8b77244c6ae398f444bb648da35406"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "masterminds_html5-2.7.6.0",
            "urls": [
                "https://api.github.com/repos/Masterminds/html5-php/zipball/897eb517a343a2281f11bc5556d6548db7d93947"
            ],
            "cacheFile": "masterminds/html5/08fb32e7137a83b9af783ead1339857fe23ac90e.zip",
            "sha256": "13303fbc8ce9e49c8229911922b83d06109deb1873b36b29050ec09af563d589"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "monolog_monolog-3.2.0.0",
            "urls": [
                "https://api.github.com/repos/Seldaek/monolog/zipball/305444bc6fb6c89e490f4b34fa6e979584d7fa81"
            ],
            "cacheFile": "monolog/monolog/50bd3361742360c2231ac757414509e58b4f9f4a.zip",
            "sha256": "2aef1a51ee450fbc1285d5c3cdc2687ff22377977eca04ae39b268820d51a8af"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "nette_schema-1.2.3.0",
            "urls": [
                "https://api.github.com/repos/nette/schema/zipball/abbdbb70e0245d5f3bf77874cea1dfb0c930d06f"
            ],
            "cacheFile": "nette/schema/34af605f2e76f1123861e91e0fa1dae2bf859457.zip",
            "sha256": "b840b5cf98b9a7bd6edc3f34fdeef688106127e2ca917b015eb55e096a7c289a"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "nette_utils-3.2.9.0",
            "urls": [
                "https://api.github.com/repos/nette/utils/zipball/c91bac3470c34b2ecd5400f6e6fdf0b64a836a5c"
            ],
            "cacheFile": "nette/utils/13e0e5c85e596b8ac64a9f8524ce8b43358a7ea4.zip",
            "sha256": "c5854a9d0d0b94986e046c0c7e7380468b9ad9ed72a06b2c2cbd93538558d02e"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "psr_cache-3.0.0.0",
            "urls": [
                "https://api.github.com/repos/php-fig/cache/zipball/aa5030cfa5405eccfdcb1083ce040c2cb8d253bf"
            ],
            "cacheFile": "psr/cache/b7eac5d329f3f43db02b28fa0fef1a15080f3536.zip",
            "sha256": "88d63083b654a7ca847e926fcf8e3c35b0a7dd1bde960d8674ba10b2b8f4361f"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "psr_container-2.0.2.0",
            "urls": [
                "https://api.github.com/repos/php-fig/container/zipball/c71ecc56dfe541dbd90c5360474fbc405f8d5963"
            ],
            "cacheFile": "psr/container/a0a43e15cb16e3ab95a991e1bffc813474b15cdf.zip",
            "sha256": "3111f5b69d3a0f690f5f92d7aeacfb247f5ebd3c175088cce4b098e5d1b06ad7"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "psr_event-dispatcher-1.0.0.0",
            "urls": [
                "https://api.github.com/repos/php-fig/event-dispatcher/zipball/dbefd12671e8a14ec7f180cab83036ed26714bb0"
            ],
            "cacheFile": "psr/event-dispatcher/8f60a8cd1b7ff4e8f9782d70d78dee877a526529.zip",
            "sha256": "4d6a674cfd89a9957ead82e31ee4df785b2b1d215693add73184729a9a66d116"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "psr_http-message-1.0.1.0",
            "urls": [
                "https://api.github.com/repos/php-fig/http-message/zipball/f6561bf28d520154e4b0ec72be95418abe6d9363"
            ],
            "cacheFile": "psr/http-message/cc1d4e9ee13f2053b80c08976256789bf3be5256.zip",
            "sha256": "8538467ca2665fe15574f4d2506871823f71fd24b9a9284aae2ba90d8f69ada4"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "psr_log-3.0.0.0",
            "urls": [
                "https://api.github.com/repos/php-fig/log/zipball/fe5ea303b0887d5caefd3d431c3e61ad47037001"
            ],
            "cacheFile": "psr/log/4109d4b3f74b78a13cb175029bcb2384f59f0a52.zip",
            "sha256": "bbc23516c85615f2f85b707bc10ba26e62033e2afd696e075575b68dc6e31928"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_apache-pack-1.0.1.0",
            "urls": [
                "https://api.github.com/repos/symfony/apache-pack/zipball/3aa5818d73ad2551281fc58a75afd9ca82622e6c"
            ],
            "cacheFile": "symfony/apache-pack/fb283ab9da5768ac84cc04d17d491aca1004aaab.zip",
            "sha256": "66cfdb5c3e675e9d0f63c36511e7fdd9ac7b0f09be56ef19d64c0efb112c621e"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_asset-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/asset/zipball/925ca9e357159b5ceeb3c4451362f0a183414162"
            ],
            "cacheFile": "symfony/asset/7027be1050ca2ff72efe6b4ee9aaac2f74dfa80e.zip",
            "sha256": "739f52d2aa27362ce8fdaf1c0329928c4afb54d27914b47faf022da06dc1cbc8"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_cache-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/cache/zipball/cfe2d7c87d55b04cbde8fe3c137d9dd66e5d83f4"
            ],
            "cacheFile": "symfony/cache/b7b169aa11b48573fc14c1405c88e6e3fea2d94d.zip",
            "sha256": "cb1d157abe09fa274f15c4c88defd04cba630ecd9dd0dd20cd59e9de78c1da85"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_cache-contracts-3.2.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/cache-contracts/zipball/e8d1a5fc43534063204b74c080ebe36307d12271"
            ],
            "cacheFile": "symfony/cache-contracts/85a7a27b8ae39a1f53cd96857c6439b73c1c9fd4.zip",
            "sha256": "5945209efaddcaa5ab16a0d9138afc11ebf7a6f194ab91b46bb4552ede327ffe"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_config-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/config/zipball/f31b3c78a3650157188a240695e688d6a182aa91"
            ],
            "cacheFile": "symfony/config/8812a087fca1d918350d7c6cee4f32727cbbbdb6.zip",
            "sha256": "8a704d9f5a4751dcd4d2d17e3a9ccf6e4f9673f5b273159d2e0616de600c13c9"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_console-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/console/zipball/3e294254f2191762c1d137aed4b94e966965e985"
            ],
            "cacheFile": "symfony/console/e0c1fc307c9477a09b9588e0c67a82d4a2831ff6.zip",
            "sha256": "3ac4ce71a9db229124258e0c7b92beeacf015c87f746cc9d37449ab175db1051"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_dependency-injection-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/dependency-injection/zipball/6abd5658d0f7fea98f882a911bfdb8795d189509"
            ],
            "cacheFile": "symfony/dependency-injection/f1852a451d25c0ca556c2df6165efa90003d5783.zip",
            "sha256": "77688650d2aac072fc03a75c2b6fe6379d5f22c6b87ff7b22ebce883755e84b8"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_deprecation-contracts-3.2.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/deprecation-contracts/zipball/1ee04c65529dea5d8744774d474e7cbd2f1206d3"
            ],
            "cacheFile": "symfony/deprecation-contracts/ae67bce021ec48f10fcd4830564406f3c0d481b4.zip",
            "sha256": "c7e6575640ea31393dcf6a529534f1eef6ddfe2b29fb55a654a438a542ef9c32"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_doctrine-bridge-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/doctrine-bridge/zipball/3d42ae343f74a67991d9da7a42eb21e4d9c3d070"
            ],
            "cacheFile": "symfony/doctrine-bridge/19aa998e406c9db02cddc2e1497ed689d433c896.zip",
            "sha256": "2d6790de675091e3cb3ed8d93b484321de89b5f78d148356727340cb1737d0c9"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_dotenv-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/dotenv/zipball/1a24cb3ab1dbb8834a75c9d46e427e84baae29bc"
            ],
            "cacheFile": "symfony/dotenv/acdb0da78392d9b2930872b10a4fd3bfa0331237.zip",
            "sha256": "bc94170170dea2a1a6600da3c5e80aea6f796e8c10dea3b636baacc7ef40fbc0"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_error-handler-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/error-handler/zipball/0092696af0be8e6124b042fbe2890ca1788d7b28"
            ],
            "cacheFile": "symfony/error-handler/3d700c05656abd282415b6356b478cf3b295a83c.zip",
            "sha256": "e611e43d52bf81bfde5f088533dbd3eced269bc48e3f1dbde096b6b9990edae6"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_event-dispatcher-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/event-dispatcher/zipball/f02d108b5e9fd4a6245aa73a9d2df2ec060c3e68"
            ],
            "cacheFile": "symfony/event-dispatcher/fe39a96323a6c870c77720869ec608aef72a7fb4.zip",
            "sha256": "85191ff863c7fbf59a9088f09103641e96a3007f0d099c76697233b7ecfded39"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_event-dispatcher-contracts-3.2.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/event-dispatcher-contracts/zipball/0782b0b52a737a05b4383d0df35a474303cabdae"
            ],
            "cacheFile": "symfony/event-dispatcher-contracts/5b84854b31d46922178c9a6363849dbf1884c8ca.zip",
            "sha256": "b65e7dfd381016a7c436c224ce0efef031a45226840dfbdfc1d79c7d907bf744"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_expression-language-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/expression-language/zipball/c61e4bbaff98b2e0b911612ef684f9b1dd3c7db4"
            ],
            "cacheFile": "symfony/expression-language/4e799cb5dd56fa694cd53d43a79087111414b963.zip",
            "sha256": "edb46e46c4eab526327be1d432e8240f32f378ca9b6558b49c05910ee1b67eac"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_filesystem-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/filesystem/zipball/e59e8a4006afd7f5654786a83b4fcb8da98f4593"
            ],
            "cacheFile": "symfony/filesystem/78315b8fe24ac07e9264d3d2f45fe613a701c934.zip",
            "sha256": "e4c695fcf540c9280db10ab9b5613363516394bcf989489e9640a6832edd3d4a"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_finder-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/finder/zipball/c90dc446976a612e3312a97a6ec0069ab0c2099c"
            ],
            "cacheFile": "symfony/finder/b733771802f34a382644737cc1850ecf8caaf472.zip",
            "sha256": "ea883c0b7ba01d0d1f6ad2d15bdff868c84086e1fc1e2e490989bc54b5e0d7b9"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_flex-2.2.4.0",
            "urls": [
                "https://api.github.com/repos/symfony/flex/zipball/52baff1adb29faf443c6710cb775bd88b9627381"
            ],
            "cacheFile": "symfony/flex/04948483055a789c94a9f44dbcf39a611301adb0.zip",
            "sha256": "fe520582117c874d7383d1017dcb56907bc7e601ecd23fbdb258c6b3bb20d2e9"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_form-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/form/zipball/5504c29b365c814132c087136935b50849411b09"
            ],
            "cacheFile": "symfony/form/12ec6af696681c9b4115c18b882417cbddad3a71.zip",
            "sha256": "f605b2b8be18b65fe7348644dd24906cb0140c1ec549ddfb1852be46aefd9f2d"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_framework-bundle-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/framework-bundle/zipball/3f6ea83b11b24271bb86deb82f915fb08621b964"
            ],
            "cacheFile": "symfony/framework-bundle/c0a2fa840e63fa602ca45d50fe4be4192b2e2ea9.zip",
            "sha256": "c701a7450daa3ad539693170543fe3fd7327777fe00ed3c7b7acb2eb379d77aa"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_html-sanitizer-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/html-sanitizer/zipball/9f7eb169f929b6f75fee7218a128856a63694cc6"
            ],
            "cacheFile": "symfony/html-sanitizer/a1a77e4d2f3055f794aa57a60c086b6612fc82db.zip",
            "sha256": "60afac693b5b085e45b1b0e0c7f5f060d6b85ee12a4e8f044f900dbd335f12b4"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_http-client-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/http-client/zipball/c5e5b772033eae96ae82f2190546399ad18c1373"
            ],
            "cacheFile": "symfony/http-client/1660a8682b14c5f0643b6fb63695fc5d6446c020.zip",
            "sha256": "51543f5a8ea2e35e7ff3260165b3171af55a9cc4e7c6b411135554bc23a12e28"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_http-client-contracts-3.2.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/http-client-contracts/zipball/c5f587eb445224ddfeb05b5ee703476742d730bf"
            ],
            "cacheFile": "symfony/http-client-contracts/c8d0d3d0efd74c17ab73df65b28214bf0bea9995.zip",
            "sha256": "3a0603189ba2dea1707526c5581307ed2fd79dbf530d214cc366acf57cf37b31"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_http-foundation-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/http-foundation/zipball/9d081ead9d3432e2e8002178d14c4c9dd4b8ffbf"
            ],
            "cacheFile": "symfony/http-foundation/d586a54647c5176aa06056011e59205eecaff6f8.zip",
            "sha256": "2d294f3ab4732f3a96a8bf263215e4529bbd015411d8df25cef7d8a7bd7bf0cc"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_http-kernel-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/http-kernel/zipball/f68aaa11eee6b21c99bce0f3d98815924888fe62"
            ],
            "cacheFile": "symfony/http-kernel/82f6fde7c524b1cc170f764dc866e1c45642a489.zip",
            "sha256": "69a668357d6e2a94bfd27521424766347adf90d09221f36477acfda434d2b566"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_intl-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/intl/zipball/3e5671e7676723db90a1b3c0b8b27e00407d69d5"
            ],
            "cacheFile": "symfony/intl/a53d518fc262223b8cf0ac393cc4749055c41fdd.zip",
            "sha256": "d11db3b73929570ccb2849287e19c8065eb9d90769cc7575dcdc068f5d295a0b"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_mailer-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/mailer/zipball/29729ac0b4e5113f24c39c46746bd6afb79e0aaa"
            ],
            "cacheFile": "symfony/mailer/755fb7a4b6b7c2ff752c353bfa09d9951310f114.zip",
            "sha256": "957b6ee4a03498c8e786b4547c5b201b19d121c0528e34f60107b026f07323e5"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_mime-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/mime/zipball/4b7b349f67d15cd0639955c8179a76c89f6fd610"
            ],
            "cacheFile": "symfony/mime/d908feb114a100fd19801f8e40a965008e32819e.zip",
            "sha256": "452bfc1f34de88ee3ba43d34a596dc6d7ab4b5d0efb2594e0191309a27e6cfad"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_monolog-bridge-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/monolog-bridge/zipball/7dedf89edf3baba78d4024e37d8b423e1ac3f079"
            ],
            "cacheFile": "symfony/monolog-bridge/27aef2243ba7b63dc12ce4930b3eb47f84e7d652.zip",
            "sha256": "c79c5e3d40b2d2449120ba5af87892f6e4f4a8b87779aa3a2dbfab60d1e507e6"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_monolog-bundle-3.8.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/monolog-bundle/zipball/a41bbcdc1105603b6d73a7d9a43a3788f8e0fb7d"
            ],
            "cacheFile": "symfony/monolog-bundle/4f7c43127ae12a5d0bebc28db86c81606a5f8c0d.zip",
            "sha256": "6a2253726b5b4d06558d96b67a5e01babd1f86e1d47fb28c907256dc335b008f"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_options-resolver-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/options-resolver/zipball/e8324d44f5af99ec2ccec849934a242f64458f86"
            ],
            "cacheFile": "symfony/options-resolver/6a7924b121db922fe7d53117697c90f4ea0f5948.zip",
            "sha256": "aa15e71267251b548bcd2666048baa5dcd7dc806f57773cb20a32cb7fc50c3a4"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_password-hasher-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/password-hasher/zipball/56aabf1c3f579c109b573d45a00a272d6abdfc81"
            ],
            "cacheFile": "symfony/password-hasher/6873e656107b75bc0d314b5ef14e18f4b0e9e68f.zip",
            "sha256": "ba737b53c32d2534852cb20441ab72890de358e40eef0d7358f4865f11e40b8f"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_polyfill-ctype-1.27.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/polyfill-ctype/zipball/5bbc823adecdae860bb64756d639ecfec17b050a"
            ],
            "cacheFile": "symfony/polyfill-ctype/04e84c03a82a82c09eaa688b17b523570f9d14d2.zip",
            "sha256": "66f212bc73088271dbbec1f3b1c3ba21171e4c5ab38676c4d151441f3e38db6f"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_polyfill-intl-grapheme-1.27.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/polyfill-intl-grapheme/zipball/511a08c03c1960e08a883f4cffcacd219b758354"
            ],
            "cacheFile": "symfony/polyfill-intl-grapheme/3e0defb9f075160deb0ea7188610275ee40a9b00.zip",
            "sha256": "11c409622d2321bfdd2fd1efdbdeaaba95da5211256f6cfdb4e003d7bd7eda45"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_polyfill-intl-icu-1.27.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/polyfill-intl-icu/zipball/a3d9148e2c363588e05abbdd4ee4f971f0a5330c"
            ],
            "cacheFile": "symfony/polyfill-intl-icu/a30753631d9bce44930aef035dedffcf5743bfa9.zip",
            "sha256": "08a14fc876482e7c56c33f8528f70c438e8e3fbf3cc85ce446d4a19f8dad964e"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_polyfill-intl-idn-1.27.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/polyfill-intl-idn/zipball/639084e360537a19f9ee352433b84ce831f3d2da"
            ],
            "cacheFile": "symfony/polyfill-intl-idn/c8495253150c4daacaf90487f77a76fc7122c16b.zip",
            "sha256": "b2ff6b6408861c6c8c486fcb3bd2109438d5d6ced9175250cfbef1e596665cc4"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_polyfill-intl-messageformatter-1.27.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/polyfill-intl-messageformatter/zipball/861fe322b162bc23822a1ee0bd62d5c7eef8c6c7"
            ],
            "cacheFile": "symfony/polyfill-intl-messageformatter/88147a0a0b6e7347a52d64f470b77dd3ce7c5e08.zip",
            "sha256": "59ce8c059ad9c934b2f8f8f6ad7b1b8206f21fa6747b5051fbebb0879efeb970"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_polyfill-intl-normalizer-1.27.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/polyfill-intl-normalizer/zipball/19bd1e4fcd5b91116f14d8533c57831ed00571b6"
            ],
            "cacheFile": "symfony/polyfill-intl-normalizer/3282f96073427a186419bc5ae65aa6726d0f143b.zip",
            "sha256": "22bf30d7b50aabe1846e3ffbc03011903e05f4208d3bb49b373c4e5fe09500b5"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_polyfill-mbstring-1.27.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/polyfill-mbstring/zipball/8ad114f6b39e2c98a8b0e3bd907732c207c2b534"
            ],
            "cacheFile": "symfony/polyfill-mbstring/7061da8bfb2a98acfbdcaf076c3ba5f167d856cc.zip",
            "sha256": "b112101451a1f76a0cb4edd6595a5733059fd2f7a4cd4d36052526602e26a8fa"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_property-access-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/property-access/zipball/cfd63e46c8b8a97f05353fb9341bfa75a62184e1"
            ],
            "cacheFile": "symfony/property-access/a57afa39aeb636e40c7e774c6adf8ed9d3d6a012.zip",
            "sha256": "77fb3cffe8b6bc18cd95f4f5910bb8433bd49025e4baf1388698b25fbfcdefdf"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_property-info-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/property-info/zipball/267c798e87dc56dd0832c29cf9012ac983ed7194"
            ],
            "cacheFile": "symfony/property-info/8b01c38cc8e3e6033072456364c228da89739580.zip",
            "sha256": "8db3fa46b82806f53d6fc9e31cd81d491ddc3ddbb3608e113419c0cd666db8de"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_routing-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/routing/zipball/589bd742d5d03c192c8521911680fe88f61712fe"
            ],
            "cacheFile": "symfony/routing/38e0c81140904718bf36e8886b84e9f00c326853.zip",
            "sha256": "cef6f614a6e4c26be7949fb25f720a8c2daf5c23eb7f46e41654c17897ba653d"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_runtime-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/runtime/zipball/bf27ed7b4317982b06f8cc37255b8a315d5a9686"
            ],
            "cacheFile": "symfony/runtime/91d8de0ad50838e2172da4043140720db9506dd7.zip",
            "sha256": "b6e0b5a5849f655e91850142a7a9a6d395d8af9eaf4887d3f1045c313e1f9792"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_security-bundle-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/security-bundle/zipball/2f7f0b79b2acb6f497e8a8f24ff86a5d7e36170f"
            ],
            "cacheFile": "symfony/security-bundle/4e2a4c4414732a7da470bacbb77e668457a5531d.zip",
            "sha256": "91e6d3ab316dbc716af54c67ea64b61f2e1c70dec9e57cb846741c9ef602e494"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_security-core-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/security-core/zipball/3a26ddeda71fbbc6419578af526f4130cea3cc38"
            ],
            "cacheFile": "symfony/security-core/9b7d61c05f54a05c1b208a1e5d45b83759abcada.zip",
            "sha256": "c1f645278fccd9936c3e62c4c349a32a504dc3101fcb81289168349a2aaec11b"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_security-csrf-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/security-csrf/zipball/4abbe66efe965bec1dc0ea04b72c361971c4000d"
            ],
            "cacheFile": "symfony/security-csrf/7c71266b4f0ed8a530779a15a1121b3710a61e56.zip",
            "sha256": "5539234414f8ea10c7c91d36be2af1066f459e7438f039cb2fc0ec940ef9b95f"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_security-http-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/security-http/zipball/5c8f064e34f3a320ab02874bdc4591197ba05b20"
            ],
            "cacheFile": "symfony/security-http/c2942169765f5a21a7db808447be0acdb36d28c9.zip",
            "sha256": "d8af69532913a3972f60320d3e8282dd3fef3eae7b4be0472027a353e5f2d399"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_service-contracts-3.2.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/service-contracts/zipball/aac98028c69df04ee77eb69b96b86ee51fbf4b75"
            ],
            "cacheFile": "symfony/service-contracts/934efdb6eaca0bae922a0d7a6b33c72f0155cdd3.zip",
            "sha256": "bdf3e104dd4765dcd54f57ab308ce585a1c1e19deb9f9679a9441ee5ddc0cd97"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_stopwatch-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/stopwatch/zipball/00b6ac156aacffc53487c930e0ab14587a6607f6"
            ],
            "cacheFile": "symfony/stopwatch/b85b4a7ad1c02983050695bb9dde57b34aa10a32.zip",
            "sha256": "d2b98f8af93f37dc7cc8f69032094e03e9df594d46dab76e2aa13caf0c0dfc39"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_string-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/string/zipball/b2dac0fa27b1ac0f9c0c0b23b43977f12308d0b0"
            ],
            "cacheFile": "symfony/string/8eaa299fe3a28225f7a03c204ea3b8a9b72a7670.zip",
            "sha256": "f60b0a7a13e346f0f8a90b6d692207c53565cfa47f9edcb98583ae388702d3b4"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_translation-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/translation/zipball/60556925a703cfbc1581cde3b3f35b0bb0ea904c"
            ],
            "cacheFile": "symfony/translation/3939f6386aec40578016c9efb54c2f8107fa8bf8.zip",
            "sha256": "14f4f0f2c007814d3634452b96f72c2218aed45934fdc9cee232f761dfefa22d"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_translation-contracts-3.2.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/translation-contracts/zipball/68cce71402305a015f8c1589bfada1280dc64fe7"
            ],
            "cacheFile": "symfony/translation-contracts/91e654b6d3791babf6a13e83165651b89bc5ff84.zip",
            "sha256": "b1a65e735e418678371bc98b68895b2fb0eea8248fdb24685b0fc6ce157b569f"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_twig-bridge-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/twig-bridge/zipball/c3ba1d52a74e583f13490eaa67b396d7feb7bab5"
            ],
            "cacheFile": "symfony/twig-bridge/b8d84d1399824eb64173e6386d4a6d11b5da565a.zip",
            "sha256": "9067752b3fbbec47f6bfedeff810402adbe06fc8a40fa63722b587e774cfdc04"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_twig-bundle-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/twig-bundle/zipball/6f3b623ca55c52862b387e1aaf1f0378e54a7a73"
            ],
            "cacheFile": "symfony/twig-bundle/d8a0fb13cc812b8f26288bf030fdfc6cd2c14d72.zip",
            "sha256": "969d2212739ebc0e90e114747d65133e411e2b06440a914c317b27315b654074"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_validator-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/validator/zipball/0ebfbe384790e61147e3d7f4aa0afbd6190198c4"
            ],
            "cacheFile": "symfony/validator/934c8054f7f2c6542ebb75e868f36ba301f4870f.zip",
            "sha256": "8db0cba89702bdd1757856f95f0473da201e4e53d7bad6092f70a9d3d993e3b1"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_var-dumper-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/var-dumper/zipball/44b7b81749fd20c1bdf4946c041050e22bc8da27"
            ],
            "cacheFile": "symfony/var-dumper/31801adef0a32006363d17d86392454f62503fda.zip",
            "sha256": "ec63c388294be62b67bb95a5c298b21bb69f8274c19ff6b57304fe7449cd31d3"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_var-exporter-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/var-exporter/zipball/108f9c6451eea8e04a7fb83bbacb5b812ef30e35"
            ],
            "cacheFile": "symfony/var-exporter/e092f9fe7874c1d28c115d9de375466075af111a.zip",
            "sha256": "58d3f1fdd1c1ae43f3df2cfcadb9789362e0d2b5253bb1958f06885a9b55f3f1"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_webpack-encore-bundle-1.16.1.0",
            "urls": [
                "https://api.github.com/repos/symfony/webpack-encore-bundle/zipball/1862d71e483769b40278548a30e756ce13ef9d4c"
            ],
            "cacheFile": "symfony/webpack-encore-bundle/1ff3f5a287e4e0ee4366e1316e9893f091033deb.zip",
            "sha256": "feff516bf45f0e802368aec1557ae491cf27fde8e063501af1054b16eef6f415"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_yaml-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/yaml/zipball/2bbfbdacc8a15574f8440c4838ce0d7bb6c86b19"
            ],
            "cacheFile": "symfony/yaml/fe0cea279581bb6637ba6aa4a10419fd051a5596.zip",
            "sha256": "b0cbaf4ceaafe20ed494322d99b08ded8e91bfa90141b1c90651d835e2015720"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "twig_extra-bundle-3.5.0.0",
            "urls": [
                "https://api.github.com/repos/twigphp/twig-extra-bundle/zipball/edfcdbdc943b52101011d57ec546af393dc56537"
            ],
            "cacheFile": "twig/extra-bundle/127b0b7f4ff0632e990c0597d1ba40ed3cc1ef37.zip",
            "sha256": "9498fdc008c4eb4ea7dca9d191135470d5585ff7e6584c4ef50442655349dc9a"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "twig_intl-extra-3.5.0.0",
            "urls": [
                "https://api.github.com/repos/twigphp/intl-extra/zipball/92f2c73471e077d0f72195a331c9a245da2010cd"
            ],
            "cacheFile": "twig/intl-extra/566bfba2b5a2e3ae635cfe5e252a3bb4d2c3e7c5.zip",
            "sha256": "3e3cb0aab31ab506d0e694d1905eab86d9b1116fb358cde30907431b322fd25a"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "twig_markdown-extra-3.5.0.0",
            "urls": [
                "https://api.github.com/repos/twigphp/markdown-extra/zipball/cad864a40c914f682ff08d909e6bdebe5c5ed134"
            ],
            "cacheFile": "twig/markdown-extra/8ee754907211952d5eeaaba31abac334434f660b.zip",
            "sha256": "b05db5b841189e3f543fefd0ae2e8805562e0a923b801f588ac0a857d839a194"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "twig_twig-3.5.0.0",
            "urls": [
                "https://api.github.com/repos/twigphp/Twig/zipball/3ffcf4b7d890770466da3b2666f82ac054e7ec72"
            ],
            "cacheFile": "twig/twig/d7c549985ef0021d5972b6ff622c92a697785750.zip",
            "sha256": "03c1bb78072911102a4cb9bcfcd867a79975fae3099464e5d7f82cbddfc3a0d2"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "dama_doctrine-test-bundle-7.1.1.0",
            "urls": [
                "https://api.github.com/repos/dmaicher/doctrine-test-bundle/zipball/279a554556bed387a6aaae0c13cc982d4874773b"
            ],
            "cacheFile": "dama/doctrine-test-bundle/200257585b9a249b36e84ac42f69ace28fb6cbd7.zip",
            "sha256": "25ca5076be748c6589a45d31c43f38e8789d1773c7b192644e00f867ce3b7519"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_data-fixtures-1.6.3.0",
            "urls": [
                "https://api.github.com/repos/doctrine/data-fixtures/zipball/c27821d038e64f1bfc852a94064d65d2a75ad01f"
            ],
            "cacheFile": "doctrine/data-fixtures/6fc9ed780bea51853d35143086424abecdc7e8ed.zip",
            "sha256": "fbfede12638042cb3702e0e97013e8c53d548adc4333286e966ab1fa9fda211b"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_doctrine-fixtures-bundle-3.4.2.0",
            "urls": [
                "https://api.github.com/repos/doctrine/DoctrineFixturesBundle/zipball/601988c5b46dbd20a0f886f967210aba378a6fd5"
            ],
            "cacheFile": "doctrine/doctrine-fixtures-bundle/c02fc4f1ca8abf546b600dd2c7e55afb9321e7c9.zip",
            "sha256": "b77d30128ce1bbc4c4cee2bc8f30fb40533bf4d4c603ac7ae5e7fa475a8759eb"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "nikic_php-parser-4.15.3.0",
            "urls": [
                "https://api.github.com/repos/nikic/PHP-Parser/zipball/570e980a201d8ed0236b0a62ddf2c9cbb2034039"
            ],
            "cacheFile": "nikic/php-parser/d82d7114a2384784c2ec20cf1dd8fd2ac538f2ba.zip",
            "sha256": "b9d68a41dc37fdb939e2200911ac0610fd37e4169a3171a0eb3a13e5e5b570e0"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "phpstan_extension-installer-1.2.0.0",
            "urls": [
                "https://api.github.com/repos/phpstan/extension-installer/zipball/f06dbb052ddc394e7896fcd1cfcd533f9f6ace40"
            ],
            "cacheFile": "phpstan/extension-installer/58bdcbd2f3b9475ecfc6b5500e8c93e26cfa8170.zip",
            "sha256": "e0bf32c22430aa13c126934e220c857e2a6438b4d7273606056681fac1caad57"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "phpstan_phpstan-1.9.14.0",
            "urls": [
                "https://api.github.com/repos/phpstan/phpstan/zipball/e5fcc96289cf737304286a9b505fbed091f02e58"
            ],
            "cacheFile": "phpstan/phpstan/5e7fb17b0265289533088409f7e2340631af002b.zip",
            "sha256": "33dba813c75432315c90f3131144309899a3386ab430d96a8f88cedb8432ae94"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "phpstan_phpstan-doctrine-1.3.32.0",
            "urls": [
                "https://api.github.com/repos/phpstan/phpstan-doctrine/zipball/4534559a8c08ab3648c6fa09289478780e190ae7"
            ],
            "cacheFile": "phpstan/phpstan-doctrine/ad3ead240c7d39c6eb7774626a9ef6a7bfaf3522.zip",
            "sha256": "6770185fc6e4495e77b23c34b99d926f0eac9cae12b206ec5adc0eeb2071bbb9"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "phpstan_phpstan-symfony-1.2.20.0",
            "urls": [
                "https://api.github.com/repos/phpstan/phpstan-symfony/zipball/d89a521e7e31822409bf37f70691f7a12a6e7d76"
            ],
            "cacheFile": "phpstan/phpstan-symfony/eabda8edf16d563e6d8ef1e3a35acef125006cd3.zip",
            "sha256": "7f79fe1d8590fe311a5d6e83afbc27edd021ec267d3f45e68f6e4efa9ef7d8a6"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_browser-kit-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/browser-kit/zipball/ea591a69d714216d29cb67b519b509bd32b735a2"
            ],
            "cacheFile": "symfony/browser-kit/bc1673927161262afe3672e48ff13b32987d4981.zip",
            "sha256": "639b6d08132837fea2a3c80341f4641ec59089904cba6cb9e23a2b3366d8db81"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_css-selector-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/css-selector/zipball/bf1b9d4ad8b1cf0dbde8b08e0135a2f6259b9ba1"
            ],
            "cacheFile": "symfony/css-selector/988efa8eede7b215aed9df8963121cdf57617147.zip",
            "sha256": "7d6d2c8e6f13ca973b041427d20328c2cf9b5edecc52c40c1d0939bb4ed99199"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_debug-bundle-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/debug-bundle/zipball/c365a0f0f6bf80f17ae9a16bc6989548746071cc"
            ],
            "cacheFile": "symfony/debug-bundle/25f468277e49b78b33f320fb054aeb3e0463a6e2.zip",
            "sha256": "72808b60462aba4f0e34561e30bc05b805a11bc15a9fcff33a4f85fa77c9c1d2"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_dom-crawler-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/dom-crawler/zipball/19aa4962a0687e96941f0bdb27b794c5b73e2394"
            ],
            "cacheFile": "symfony/dom-crawler/87fdbd7a43c34158887f70252481e44c75104adc.zip",
            "sha256": "dc43c5842ee477e6463a1e2ca833eeaa28beebe5b01cfeed995a2fac257db3cb"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_maker-bundle-1.48.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/maker-bundle/zipball/2e428e8432e9879187672fe08f1cc335e2a31dd6"
            ],
            "cacheFile": "symfony/maker-bundle/eadcc61144e21901bbbe8cdd7b55bb5bac3eb097.zip",
            "sha256": "819bb712a45a3910f623139308ad0d37b3dd55bc3bb13281a20c73e827ff5ae5"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_phpunit-bridge-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/phpunit-bridge/zipball/d759e5372de414bef53a688c7aa7e240e4fd8aa2"
            ],
            "cacheFile": "symfony/phpunit-bridge/a7acf38e7392e253b3457339b8874863993759e3.zip",
            "sha256": "11208184892db77c3df753f3b0cc99d1179a884396b62012b99410289760f589"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_web-profiler-bundle-6.2.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/web-profiler-bundle/zipball/8d4b1a806ae185a735f789edfdc346c8b43d914b"
            ],
            "cacheFile": "symfony/web-profiler-bundle/0ea1771baa1c3d60d45c9a86858651256b74cdda.zip",
            "sha256": "27fe31cd9d88259fb08db12ec4ce653c652f90c5b13bf7a70383f44fdba5ce07"
        }
    ],
    "projectName": "symfony_symfony-demo"
}
  '';
  composerPath = data.composerPath or phpPackages.composer.src;
  cacheEntries = data.cacheEntries or [];
  localEntries = data.localEntries or [];

  # Shell snippet to collect all project dependencies.
  collectCacheScript = writeText "collect-cache.sh" (
    concatMapStrings (args: ''
      (
        cacheFile=${escapeShellArg args.cacheFile}
        cacheFilePath="$COMPOSER_CACHE_DIR/files/$cacheFile"
        mkdir -p "$(dirname "$cacheFilePath")"
        cp ${escapeShellArg (fetcher args)} "$cacheFilePath"
      )
    '') cacheEntries
  );

  replaceLocalPaths = writeText "replace-local-paths.sh" (
    concatMapStrings (args: ''
      sed -i -e "s|\"${args.string}\"|\"${args.path}\"|" composer.lock
    '') localEntries
  );

in stdenv.mkDerivation {
  name = data.projectName;
  inherit src;

  # Make sure the build uses the right PHP version everywhere.
  # Also include unzip for Composer.
  buildInputs = [ php unzip ];

  # Defines the shell alias to run Composer.
  postHook = ''
    composer () {
      php "$NIX_COMPOSER_PATH" "$@"
    }
  '';

  configurePhase = ''
    runHook preConfigure

    # Set the cache directory for Composer.
    export COMPOSER_CACHE_DIR="$NIX_BUILD_TOP/.composer/cache"

    # Build the cache directory contents.
    source ${collectCacheScript}

    # Replace local package paths with their Nix store equivalent.
    source ${replaceLocalPaths}

    # Store the absolute path to Composer for the 'composer' alias.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Run normal Composer install to complete dependency installation.
    composer install -n -o

    runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/libexec $out/bin

    # Move the entire project to the output directory.
    mv $PWD "$out/libexec/$sourceRoot"
    cd "$out/libexec/$sourceRoot"

    # Update the path to Composer.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Invoke a plugin internal command to setup binaries.
    # composer nixify-install-bin "$out/bin"

    runHook postInstall
  '';

  passthru = {
    inherit php;
  };
}
